# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
