# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='pub_at',
        ),
    ]
